name: ndpyramid-demo
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.10
  - dask
  - esmpy>=8.2.0
  - mpich
  - netcdf4
  - numpy
  - pip
  - pooch
  - pre-commit
  - pydantic>=1.10
  - pyproj
  - pyresample
  - rasterio
  - rioxarray
  - s3fs
  - scipy
  - sparse>=0.13.0
  - xarray
  - xarray-datatree>=0.0.11
  - xesmf
  - zarr
  - cf_xarray>=0.8.0
  - coiled
  - fastparquet
  - matplotlib
  - ipykernel
  - pip:
      - ndpyramid
